<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
<!-- Document Meta
    ============================================= -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!--IE Compatibility Meta-->
<meta name="description" content=" ai-marketinginvestment.com gives everyone an easy way to participate in the financial markets. Trade with as little as $1 USD on major currencies, stock indices, commodities, and synthetic indices." />
<meta name="keywords" content=" binary options, forex, forex trading, online trading, financial trading, binary trading, index trading, trading stock indices, forex trades, trading commodities, binary options strategy, binary broker, binary bet, binary options trading platform, binary strategy, finance, investment, trading" />
<meta name="author" content="ai-marketinginvestment.com" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href="assets/images/favicon/favicon.png" rel="icon">

<!-- Fonts
    ============================================= -->
 <link href="https://fonts.googleapis.com/css?family=Exo+2:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i%7CRoboto:300,300i,400,400i,500,500i,700,700i,900,900i%7CWork+Sans:300,400,500,600,700,800,900" rel="stylesheet">

<!-- Stylesheets
    ============================================= -->
<link rel="stylesheet" href="css/common.min.css" />
<link href="assets/css/external.css" rel="stylesheet">
<link href="assets/css/style.css" rel="stylesheet">
	


<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
<!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->

<!-- Document Title
    ============================================= -->
<title>About Us | Capitaltrade Investment </title>
</head>
<body>
<div class="preloader">
	<div class="loader-eclipse">
		<div class="loader-content"></div>
	</div>
</div><!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="wrapper clearfix">
    <?php
        require_once 'incs/header.php';
    ?>

<!-- Page Title
============================================= -->
<section id="page-title" class="page-title bg-overlay bg-overlay-dark bg-parallax">
	<div class="bg-section">
		<img src="assets/images/sliders/slide-bg/6.jpg" alt="Background"/>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12 col-lg-10 offset-lg-1">
				<div class="title title-6 text-center">
                    <div class="title--heading">
                        <h1>About-us</h1>
                    </div>
					<div class="clearfix"></div>
					<ol class="breadcrumb">
						<li><a href="index-2.html">Home</a></li>
						<li class="active">About us</li>
					</ol>
				</div><!-- .title end -->
			</div><!-- .col-lg-12 end -->
		</div><!-- .row end -->
	</div><!-- .container end -->
</section><!-- #page-title end -->

<!-- Services #1
============================================= -->
<div class="about-us box-inlay-borders static_full">
			<div class="container section">
			<div class="gr-parent">
			<h3 class="center-text gr-padding-20">The Premier platform for handsfree trading with artifical intelligence BOT that generates signals and strategies in the world&#x27;s financial markets</h3>
			<div class="gr-row"><div class="gr-6 gr-12-m gr-padding-20"><img class="mac" src="images/mac.png" /></div>
			<div class="gr-1 gr-hide-t gr-hide-p gr-hide-m"></div>
			<div class="gr-5 gr-12-m"><p>The main advantage of Capitaltrade Investment is its premium quallity in everything and there is no exceptions. Transparency of the platform, advanced technologies, attractive conditions for participants - all this makes us unique.</p><p>Using our website, customers can trade currencies, stock indices, commodities, and synthetic indices 24/7. We have the most flexible pricing and the most comprehensive suite of products available.</p><p>Ai-Marketing Investment has earned an enviable reputation for our commitment to high ethical standards and the quality of the trading experience we provide.</p><p>When you trade with Ai-marketing investment, you can be assured that you will never lose any trade/investment as your brokerage account with us is on auto stop-loss. The signals and strategies generated by our Artificial intelligence BOT is always 100% accurate. You equally have full control of your account and there is no fee charged during withdrawals from your account. </p></div></div></div>
			<div class="gr-12"><div>
			<div class="separator-line gr-padding-10 border-bottom"></div></div></div>
			<div class="gr-parent">
			<h3 class="center-text gr-padding-20" data-anchor="our-values">Our values</h3>
			<div class="gr-row"><div class="gr-6 gr-12-p gr-12-m"><div class="values-box"><div class="icon-wrapper ic-intergrity"></div>
			<div class="content-wrapper"><div><h4 class="values-box-subheader">Integrity</h4></div><div>
			<div class="separator-line header-line border-bottom"></div></div>
			<div><p class="values-box-text">We believe that we should always do the right thing. This includes serving our customers with honesty and transparency, settling all contracts by the book, and communicating in plain language that can be easily understood.</p></div></div></div></div>
			<div class="gr-6 gr-12-p gr-12-m">
			<div class="values-box">
			<div class="icon-wrapper ic-teamwork"></div>
			<div class="content-wrapper">
			<div><h4 class="values-box-subheader">Teamwork</h4></div>
			<div>
			<div class="separator-line header-line border-bottom"></div></div>
			<div><p class="values-box-text">We value positive team players who can work together to overcome challenges and achieve common goals.</p></div></div></div></div>
			<div class="gr-6 gr-12-p gr-12-m">
			<div class="values-box">
			<div class="icon-wrapper ic-competence"></div>
			<div class="content-wrapper">
			<div><h4 class="values-box-subheader">Competence</h4></div>
			<div><div class="separator-line header-line border-bottom"></div></div>
			<div><p class="values-box-text">We love to work with smart and talented people who are eager to roll up their sleeves and get things done.</p></div></div></div></div>
			<div class="gr-6 gr-12-p gr-12-m">
			<div class="values-box">
			<div class="icon-wrapper ic-customer-focus"></div>
			<div class="content-wrapper">
			<div><h4 class="values-box-subheader">Customer focus</h4></div>
			<div><div class="separator-line header-line border-bottom"></div></div>
			<div><p class="values-box-text">We always put our customers first and dedicate ourselves to building products and services that give them the best trading experience possible.</p></div></div></div></div>
			</div></div></div>
<!-- #service1 end -->

<!-- Consultation #1
============================================= -->
<section id="consultation" class="consultation consultation-1 pb-0">
    <div class="bg-section">
        <img src="assets/images/background/8.jpg" alt="Background" />
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="heading heading-2 mb-50">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-7">
                            <h2 class="heading--title text-white"><span class="text-theme">Discover</span><span class="text-white"> Thousands of Trading & Investment Opportunities.</span></h2>
                        </div>
                    </div><!-- .row end -->
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-6">
                            <p class="heading--desc">Now you can start trading cryptocurrencies, Binary, Forex, CFDs, Metals, easily and safely from where ever you are. With great margin trading leverage and short sell options available with quick deposit & withdrawal capability, you can start trading with us in seconds.</p>
                        </div>
                        <div class="col-sm-12 col-md-12 col-lg-6">
                            <p class="heading--desc">Binary, Forex, CFDs and Metals have become established investment commodities among major financial institutions, and have even been adopted by countries such as Australia and Japan. However, as with any investment there are risks linked to market movements!</p>
                        </div>
                    </div><!-- .row end -->
                </div><!-- .heading end -->
            </div>

        </div>
        <!-- .row end -->
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="consultation-form mb-30 bg-white text-center">
                    <div class="consultation--desc">
                        Request a Consultation
                    </div>
                    <form method="post" action="#" class="contactForm mb-0">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-4">
                                <input type="text" class="form-control" name="consultater-name" id="name" placeholder="Your Name" required="">
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-4">
                                <input type="email" class="form-control" name="consultater-email" id="email" placeholder="Email">
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-4">
                                <div class="form-select">
                                    <i class="fa fa-angle-down"></i>
                                    <select class="form-control" name="Cryptocurreny" id="Cryptocurreny">
                                        <option value="Cryptocurrencies">Cryptocurrencies</option>
                                        <option value="Bitcoin">Forex</option>
                                        <option value="Litecoin">Binary</option>
                                        <option value="Namecoin">Metals</option>
                                        <option value="Dogecoin">CFDs</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <textarea class="form-control" name="consultater-message" id="message" rows="2" placeholder="Request Details:"></textarea>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <input type="submit" value="Submit Request" name="submit" class="btn btn--primary btn--block">
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="contact-result"></div>
                            </div>
                        </div>
                        <!-- .row end -->
                    </form>
                    <!-- form end -->
                </div>
                <!-- .contact-form end -->
            </div>
            <!-- .col-lg-8 end -->
        </div>
    </div>
    <!-- .container end -->
</section>
<!-- #consultation end -->
<!-- Footer #1
============================================= -->
<?php
require_once 'incs/footer.php';
?>


<div id="back-to-top" class="backtop"><i class="fa fa-long-arrow-up"></i></div>
</div><!-- #wrapper end -->

<!-- Footer Scripts
============================================= -->

<script src="assets/js/jquery-3.3.1.min.js"></script>
<script src="assets/js/plugins.js"></script>
<script src="assets/js/functions.js"></script>
</body>
</html>